# Generated by Django 6.0.6 on 2026-07-04 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_app', '0002_platform_triggers'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS mdm;'),
        migrations.CreateModel(
            name='EffectiveItemStatusView',
            fields=[
                ('extension_id', models.UUIDField(primary_key=True, serialize=False)),
                ('item_id', models.UUIDField()),
                ('node_id', models.UUIDField()),
                ('global_status', models.CharField(max_length=30)),
                ('raw_local_status', models.CharField(max_length=30)),
                ('effective_status', models.CharField(max_length=30)),
                ('traceability_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"mdm"."vw_effective_item_status"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bp_number', models.CharField(max_length=100, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('tax_vat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_bp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='mdm.businesspartner')),
            ],
            options={
                'db_table': '"mdm"."business_partners"',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('item_class', models.CharField(choices=[('INVENTORY', 'Inventory'), ('SERVICE', 'Service'), ('RAW_MATERIAL', 'Raw Material'), ('ASSEMBLY', 'Assembly'), ('PHANTOM', 'Phantom')], max_length=50)),
                ('base_uom', models.CharField(max_length=20)),
                ('global_description', models.TextField()),
                ('traceability_type', models.CharField(choices=[('NONE', 'None'), ('BATCH', 'Batch Tracked'), ('SERIAL', 'Serial Tracked')], default='NONE', max_length=20)),
                ('global_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN_DEVELOPMENT', 'In Development')], default='IN_DEVELOPMENT', max_length=30)),
            ],
            options={
                'db_table': '"mdm"."items"',
                'indexes': [models.Index(fields=['global_status'], name='idx_items_status'), models.Index(fields=['item_class'], name='idx_items_class')],
            },
        ),
        migrations.CreateModel(
            name='BPNodeRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bp_role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('CARRIER', 'Carrier'), ('EMPLOYEE', 'Employee')], max_length=50)),
                ('financial_terms', models.CharField(max_length=50)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_roles', to='platform_app.node')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_roles', to='mdm.businesspartner')),
            ],
            options={
                'db_table': '"mdm"."bp_node_roles"',
                'constraints': [models.UniqueConstraint(fields=('bp', 'node', 'bp_role'), name='uq_bp_node_role')],
            },
        ),
        migrations.CreateModel(
            name='ItemNodeExtension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('PHASE_OUT', 'Phase Out'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=30)),
                ('costing_method', models.CharField(choices=[('STANDARD', 'Standard'), ('FIFO', 'FIFO'), ('MOVING_AVERAGE', 'Moving Average')], max_length=30)),
                ('replenishment_rule', models.CharField(choices=[('MAKE_TO_STOCK', 'Make to Stock'), ('MAKE_TO_ORDER', 'Make to Order'), ('BUY_TO_ORDER', 'Buy to Order'), ('NONE', 'None')], max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_extensions', to='mdm.item')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_extensions', to='platform_app.node')),
            ],
            options={
                'db_table': '"mdm"."item_node_extensions"',
                'indexes': [models.Index(fields=['node'], name='idx_item_ext_node')],
                'constraints': [models.UniqueConstraint(fields=('item', 'node'), name='uq_item_node')],
            },
        ),
    ]
