# Generated by Django 6.0.6 on 2026-07-04 16:30

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('ENTERPRISE', 'Enterprise'), ('LEGAL_ENTITY', 'Legal Entity'), ('REGION', 'Region'), ('SITE', 'Site'), ('ZONE', 'Zone'), ('BIN', 'Bin'), ('WORK_CENTER', 'Work Center'), ('LPN', 'License Plate Number')], max_length=50)),
                ('node_name', models.CharField(max_length=255)),
                ('lineage_path', core.fields.LtreeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PLANNED', 'Planned')], default='PLANNED', max_length=30)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_nodes', to='platform_app.node')),
            ],
            options={
                'db_table': 'platform_nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeAccessAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('cascade_access', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_assignments', to='platform_app.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_node_access_assignments',
            },
        ),
        migrations.CreateModel(
            name='NodeSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.JSONField()),
                ('is_override', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='platform_app.node')),
            ],
            options={
                'db_table': 'platform_node_settings',
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='idx_nodes_node_type'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['status'], name='idx_nodes_status'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_node__isnull', True)), fields=('parent_node',), name='uq_one_root_node_allowed'),
        ),
        migrations.AddConstraint(
            model_name='nodeaccessassignment',
            constraint=models.UniqueConstraint(fields=('user', 'node', 'role'), name='uq_user_node_role'),
        ),
        migrations.AddConstraint(
            model_name='nodesetting',
            constraint=models.UniqueConstraint(fields=('node', 'setting_key'), name='uq_node_setting_key'),
        ),
    ]
