# Generated by Django 6.0.6 on 2026-07-05 14:18

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0002_mdm_triggers_and_views'),
        ('platform_app', '0002_platform_triggers'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS eng;'),
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_level', models.CharField(max_length=50)),
                ('bom_type', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('ENGINEERING', 'Engineering'), ('KIT', 'Kit'), ('PHANTOM', 'Phantom')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boms', to='mdm.item')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='node_boms', to='platform_app.node')),
            ],
            options={
                'db_table': '"eng"."bom_headers"',
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('bom_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('scrap_factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('effectivity_dates', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='engineering.bomheader')),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='used_in_boms', to='mdm.item')),
            ],
            options={
                'db_table': '"eng"."bom_lines"',
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangeOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eco_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(choices=[('COST_REDUCTION', 'Cost Reduction'), ('QUALITY_FIX', 'Quality Fix'), ('OBSOLESCENCE', 'Obsolescence'), ('NPI', 'New Product Introduction')], max_length=50)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=30)),
                ('effectivity_date', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ecos', to='platform_app.node')),
                ('target_bom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ecos', to='engineering.bomheader')),
            ],
            options={
                'db_table': '"eng"."ecos"',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('routing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_seq', models.IntegerField()),
                ('standard_time', models.DecimalField(decimal_places=4, max_digits=19)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='engineering.bomheader')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='site_routings', to='platform_app.node')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_center_routings', to='platform_app.node')),
            ],
            options={
                'db_table': '"eng"."routings"',
            },
        ),
        migrations.AddIndex(
            model_name='bomheader',
            index=models.Index(fields=['item', 'node'], name='idx_bom_headers_item_node'),
        ),
        migrations.AddIndex(
            model_name='bomheader',
            index=models.Index(fields=['status'], name='idx_bom_headers_status'),
        ),
        migrations.AddConstraint(
            model_name='bomheader',
            constraint=models.UniqueConstraint(fields=('item', 'node', 'revision_level'), name='uq_item_node_revision'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['component_item'], name='idx_bom_lines_component'),
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('bom', 'operation_seq'), name='uq_routing_seq'),
        ),
    ]
