# Generated by Django 6.0.6 on 2026-07-05 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdm', '0002_mdm_triggers_and_views'),
        ('platform_app', '0002_platform_triggers'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS mes;'),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='work_center_profile', serialize=False, to='platform_app.node')),
                ('resource_type', models.CharField(choices=[('MACHINE', 'Machine'), ('LABOR_POOL', 'Labor Pool'), ('SUBCONTRACTOR', 'Subcontractor')], max_length=50)),
                ('standard_cost_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('capacity_hrs_day', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': '"mes"."work_centers"',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PLANNED', max_length=30)),
                ('actual_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manufactured_orders', to='mdm.item')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_orders', to='platform_app.node')),
            ],
            options={
                'db_table': '"mes"."work_orders"',
            },
        ),
        migrations.CreateModel(
            name='WOOperation',
            fields=[
                ('wo_op_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_seq', models.IntegerField()),
                ('yield_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('scrap_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scheduled_operations', to='mes.workcenter')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mes.workorder')),
            ],
            options={
                'db_table': '"mes"."wo_operations"',
            },
        ),
        migrations.CreateModel(
            name='WOMaterialRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=19)),
                ('consumed_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='required_in_wos', to='mdm.item')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='mes.workorder')),
            ],
            options={
                'db_table': '"mes"."wo_material_requirements"',
            },
        ),
        migrations.CreateModel(
            name='ProductionTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SETUP', 'Setup'), ('RUN', 'Run'), ('MATERIAL_ISSUE', 'Material Issue'), ('SCRAP', 'Scrap'), ('YIELD', 'Yield')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('labor_hours', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('batch_serial_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_id', models.UUIDField(db_index=True)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executed_transactions', to='mes.workcenter')),
                ('wo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='mes.workorder')),
            ],
            options={
                'db_table': '"mes"."production_transactions"',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='idx_wo_status'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['node'], name='idx_wo_node'),
        ),
        migrations.AddConstraint(
            model_name='wooperation',
            constraint=models.UniqueConstraint(fields=('wo', 'operation_seq'), name='uq_wo_op_seq'),
        ),
        migrations.AddConstraint(
            model_name='womaterialrequirement',
            constraint=models.UniqueConstraint(fields=('wo', 'component_item'), name='uq_wo_req_item'),
        ),
        migrations.AddIndex(
            model_name='productiontransaction',
            index=models.Index(fields=['batch_serial_ref'], name='idx_pt_batch'),
        ),
    ]
